//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTempSong
    {
        public int MID { get; set; }
        public string SongName { get; set; }
        public byte[] SongFile { get; set; }
    }
}
